spring:
  application:
    name: boot-jboss
  datasource:
    druid:
      # 如果是 JNDI 模式，需要配置改项
      jndiDataSourceName: java:jboss/primary_OracleXADS

      # 如果是 XA 模式，根据实际情况，需配置如下
      basePackages: com.joeylee.mapper.primary
      xmlPath: classpath*:mapper/primary/*.xml
      uniqueResourceName: oracle 1

      url: jdbc:oracle:thin:@127.0.0.1:1521/ORACLE
      username: lee_account_dev
      password: lee123456
      #      driver: oracle.jdbc.driver.OracleDriver
      initial-size: 5
      max-active: 20
      min-idle: 10
      max-wait: 10


# 多数据源配置
multi-datasource:
  enabled: XA
  datasource:
    druid:
      # 如果是 JNDI 模式，需要配置改项
      jndiDataSourceName: java:jboss/txn_log_OracleXADS

      # 如果是 XA 模式，根据实际情况，需配置如下
      basePackages: com.joeylee.mapper.second
      xmlPath: classpath*:mapper/second/*.xml
      uniqueResourceName: oracle 2

      url: jdbc:oracle:thin:@127.0.0.1:1521/ORACLE
      username: lee
      password: lee123456
      initialSize: 5
      maxActive: 20
      minIdle: 10
      maxWait: 10

#日志打印
logging:
  # 配置级别
  level:
    #分包配置级别，即不同的目录下可以使用不同的级别
    com: debug

joeylee:
  # 全局响应结果处理
  response-handler:
    enable: true
  # 全局异常处理
  exception-handler:
    enable: true
