spring:
  application:
    name: boot-atomikos
  datasource:
    druid:
      # 如果是 JNDI 模式，需要配置该项
      jndiDataSourceName: java:jboss/primary_OracleXADS

      # 如果是XA 模式，根据实际情况，需配置如下
      # Mybatis的mapper接口文件路径
      basePackages:
        -com.joeylee.mapper.primary
        -com.joey2lee.mapper.primary
      # Mybatis的mapper的xml文件路径
      xmlPath: classpath*:mapper/primary/*.xml
      # atomikos 资源名称,每个数据源必须唯一
      uniqueResourceName: primary_OracleXADS

      url: jdbc:oracle:thin:@10.1.107.105:1521/ORACLEPDB
      username: fubon_account_dev
      password: fubon123456
      #      driver: oracle.jdbc.driver.OracleDriver
      initial-size: 5
      max-active: 20
      min-idle: 10
      max-wait: 10


# 多数据源配置
multi-datasource:
  enabled: XA
  datasource:
    druid:
      # 如果是 JNDI 模式，需要配置该项
      jndiDataSourceName: java:jboss/txn_log_OracleXADS

      # 如果是 XA 模式，根据实际情况，需配置如下
      basePackages: com.joeylee.mapper.second
      xmlPath: classpath*:mapper/second/*.xml
      uniqueResourceName: oracle 2

      url: jdbc:oracle:thin:@10.1.107.105:1521/ORACLEPDB
      username: fubon
      password: fubon123456
      initialSize: 5
      maxActive: 20
      minIdle: 10
      maxWait: 10

#日志打印
logging:
  # 配置级别
  level:
    #分包配置级别，即不同的目录下可以使用不同的级别
    com: debug

joeylee:
  # 全局响应结果处理
  response-handler:
    enable: true
  # 全局异常处理
  exception-handler:
    enable: true
